namespace AIReviewer.Domain.Entities;

/// <summary>
/// Contains a suggested code fix generated by the AutoFixSuggestionGenerator.
/// </summary>
public class AutoFixResult
{
    public string OriginalFile { get; set; } = string.Empty;
    public int Line { get; set; }
    public string Issue { get; set; } = string.Empty;
    public string SuggestedCode { get; set; } = string.Empty;
    public string Explanation { get; set; } = string.Empty;
}
